-- 1
SELECT "COUNTRIES", SUM("QUANTITY") AS "QUANTITIES"
FROM beers
GROUP BY "COUNTRIES"
ORDER BY "QUANTITIES" DESC
LIMIT 1;

-- 2
SELECT "SALES_REP", SUM("PROFIT") AS "PROFITS"
FROM brewery_data
WHERE "BRANDS" = 'budweiser'
	AND "COUNTRIES" = 'Senegal'
GROUP BY "SALES_REP"
ORDER BY "PROFITS" DESC
LIMIT 1;

-- 3
SELECT "COUNTRIES", "MONTHS", SUM("PROFIT") AS "PROFITS"
FROM brewery_data
WHERE "YEARS" = 2019
	AND "MONTHS" IN ('October', 'November', 'December')
GROUP BY "COUNTRIES", "MONTHS"
ORDER BY "PROFITS" DESC
LIMIT 1;